name: Release

on:
  push:
    branches:
      - dev

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Get version from package.json
        id: package-version
        run: echo "version=$(jq -r .version package.json)" >> "$GITHUB_OUTPUT"

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Build for Cloudflare Workers
        run: pnpm build:cloudflare && cp ./.output/server/index.mjs ./cloudflare.worker.mjs

      - name: Build for AWS Lambda
        run: pnpm build:aws && cd .output/server && zip -r ../../lambda.zip .

      - name: Build for Node.js
        run: pnpm build:node && cd .output/server && zip -r ../../nodejs.zip .

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.package-version.outputs.version }}
          name: sudo-proxy v${{ steps.package-version.outputs.version }}
          generate_release_notes: true
          body: |
            Run with Docker:
            ```sh
            docker run -p 3000:3000 ghcr.io/okikio/sudo-proxy:${{ steps.package-version.outputs.version }}
            ```
          files: |
            cloudflare.worker.mjs
            lambda.zip
            nodejs.zip

